---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jira
    spec:
      restartPolicy: Always

      containers:
        - name: jira
          image: eu.gcr.io/wire-bot/jira:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: jira-knows
                  key: token

            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jira-knows
                  key: keystore_password

          volumeMounts:
            - name: jira-disk
              mountPath: /var/lib/jira

            - name: jira-config
              mountPath: /etc/jira

          command:
            - "/usr/bin/java"
            - "-Ddw.server.applicationConnectors[1].keyStorePassword=$(KEYSTORE_PASSWORD)"
            - "-Ddw.auth=$(TOKEN)"
            - "-jar"
            - "jira.jar"
            - "server"
            - "/etc/jira/jira.yaml"

      volumes:
        - name: jira-disk
          gcePersistentDisk:
            pdName: jira-disk
            fsType: ext4

        - name: jira-config
          configMap:
            name: jira-config

---

apiVersion: v1
kind: Service
metadata:
  name: jira
spec:
  selector:
    name: jira
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 4443
      protocol: TCP

    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP